import abc
from abc import ABC, abstractmethod
from collections.abc import Iterator
from pathlib import Path
from typing import Literal

from _typeshed import Incomplete

class PlatformDirsABC(ABC, metaclass=abc.ABCMeta):
    appname: Incomplete
    appauthor: Incomplete
    version: Incomplete
    roaming: Incomplete
    multipath: Incomplete
    opinion: Incomplete
    ensure_exists: Incomplete
    def __init__(
        self,
        appname: str | None = None,
        appauthor: str | Literal[False] | None = None,
        version: str | None = None,
        roaming: bool = False,
        multipath: bool = False,
        opinion: bool = True,
        ensure_exists: bool = False,
    ) -> None: ...
    @property
    @abstractmethod
    def user_data_dir(self) -> str: ...
    @property
    @abstractmethod
    def site_data_dir(self) -> str: ...
    @property
    @abstractmethod
    def user_config_dir(self) -> str: ...
    @property
    @abstractmethod
    def site_config_dir(self) -> str: ...
    @property
    @abstractmethod
    def user_cache_dir(self) -> str: ...
    @property
    @abstractmethod
    def site_cache_dir(self) -> str: ...
    @property
    @abstractmethod
    def user_state_dir(self) -> str: ...
    @property
    @abstractmethod
    def user_log_dir(self) -> str: ...
    @property
    @abstractmethod
    def user_documents_dir(self) -> str: ...
    @property
    @abstractmethod
    def user_downloads_dir(self) -> str: ...
    @property
    @abstractmethod
    def user_pictures_dir(self) -> str: ...
    @property
    @abstractmethod
    def user_videos_dir(self) -> str: ...
    @property
    @abstractmethod
    def user_music_dir(self) -> str: ...
    @property
    @abstractmethod
    def user_desktop_dir(self) -> str: ...
    @property
    @abstractmethod
    def user_runtime_dir(self) -> str: ...
    @property
    @abstractmethod
    def site_runtime_dir(self) -> str: ...
    @property
    def user_data_path(self) -> Path: ...
    @property
    def site_data_path(self) -> Path: ...
    @property
    def user_config_path(self) -> Path: ...
    @property
    def site_config_path(self) -> Path: ...
    @property
    def user_cache_path(self) -> Path: ...
    @property
    def site_cache_path(self) -> Path: ...
    @property
    def user_state_path(self) -> Path: ...
    @property
    def user_log_path(self) -> Path: ...
    @property
    def user_documents_path(self) -> Path: ...
    @property
    def user_downloads_path(self) -> Path: ...
    @property
    def user_pictures_path(self) -> Path: ...
    @property
    def user_videos_path(self) -> Path: ...
    @property
    def user_music_path(self) -> Path: ...
    @property
    def user_desktop_path(self) -> Path: ...
    @property
    def user_runtime_path(self) -> Path: ...
    @property
    def site_runtime_path(self) -> Path: ...
    def iter_config_dirs(self) -> Iterator[str]: ...
    def iter_data_dirs(self) -> Iterator[str]: ...
    def iter_cache_dirs(self) -> Iterator[str]: ...
    def iter_runtime_dirs(self) -> Iterator[str]: ...
    def iter_config_paths(self) -> Iterator[Path]: ...
    def iter_data_paths(self) -> Iterator[Path]: ...
    def iter_cache_paths(self) -> Iterator[Path]: ...
    def iter_runtime_paths(self) -> Iterator[Path]: ...
