from pathlib import Path

from .api import PlatformDirsABC

__all__ = ["MacOS"]

class MacOS(PlatformDirsABC):
    @property
    def user_data_dir(self) -> str: ...
    @property
    def site_data_dir(self) -> str: ...
    @property
    def site_data_path(self) -> Path: ...
    @property
    def user_config_dir(self) -> str: ...
    @property
    def site_config_dir(self) -> str: ...
    @property
    def user_cache_dir(self) -> str: ...
    @property
    def site_cache_dir(self) -> str: ...
    @property
    def site_cache_path(self) -> Path: ...
    @property
    def user_state_dir(self) -> str: ...
    @property
    def user_log_dir(self) -> str: ...
    @property
    def user_documents_dir(self) -> str: ...
    @property
    def user_downloads_dir(self) -> str: ...
    @property
    def user_pictures_dir(self) -> str: ...
    @property
    def user_videos_dir(self) -> str: ...
    @property
    def user_music_dir(self) -> str: ...
    @property
    def user_desktop_dir(self) -> str: ...
    @property
    def user_runtime_dir(self) -> str: ...
    @property
    def site_runtime_dir(self) -> str: ...
